package com.gntcyouthbe.bible.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum BookName {

    GENESIS("창세기"),
    EXODUS("출애굽기"),
    LEVITICUS("레위기"),
    NUMBERS("민수기"),
    DEUTERONOMY("신명기"),
    JOSHUA("여호수아"),
    JUDGES("사사기"),
    RUTH("룻기"),
    FIRST_SAMUEL("사무엘상"),
    SECOND_SAMUEL("사무엘하"),
    FIRST_KINGS("열왕기상"),
    SECOND_KINGS("열왕기하"),
    FIRST_CHRONICLES("역대상"),
    SECOND_CHRONICLES("역대하"),
    EZRA("에스라"),
    NEHEMIAH("느헤미야"),
    ESTHER("에스더"),
    JOB("욥기"),
    PSALMS("시편"),
    PROVERBS("잠언"),
    ECCLESIASTES("전도서"),
    SONG_OF_SONGS("아가"),
    ISAIAH("이사야"),
    JEREMIAH("예레미야"),
    LAMENTATIONS("예레미야애가"),
    EZEKIEL("에스겔"),
    DANIEL("다니엘"),
    HOSEA("호세아"),
    JOEL("요엘"),
    AMOS("아모스"),
    OBADIAH("오바댜"),
    JONAH("요나"),
    MICAH("미가"),
    NAHUM("나훔"),
    HABAKKUK("하박국"),
    ZEPHANIAH("스바냐"),
    HAGGAI("학개"),
    ZECHARIAH("스가랴"),
    MALACHI("말라기"),
    MATTHEW("마태복음"),
    MARK("마가복음"),
    LUKE("누가복음"),
    JOHN("요한복음"),
    ACTS("사도행전"),
    ROMANS("로마서"),
    FIRST_CORINTHIANS("고린도전서"),
    SECOND_CORINTHIANS("고린도후서"),
    GALATIANS("갈라디아서"),
    EPHESIANS("에베소서"),
    PHILIPPIANS("빌립보서"),
    COLOSSIANS("골로새서"),
    FIRST_THESSALONIANS("데살로니가전서"),
    SECOND_THESSALONIANS("데살로니가후서"),
    FIRST_TIMOTHY("디모데전서"),
    SECOND_TIMOTHY("디모데후서"),
    TITUS("디도서"),
    PHILEMON("빌레몬서"),
    HEBREWS("히브리서"),
    JAMES("야고보서"),
    FIRST_PETER("베드로전서"),
    SECOND_PETER("베드로후서"),
    FIRST_JOHN("요한일서"),
    SECOND_JOHN("요한이서"),
    THIRD_JOHN("요한삼서"),
    JUDE("유다서"),
    REVELATION("요한계시록");

    private final String displayName;
}
